theme: jekyll-theme-slate

# Site settings
title: "AI, Data and Physics"
name: "Woo-Sung Jung"
description: "인공지능과 빅데이터. 물리학과는 별 상관없는 이야기라고요? 물리학자들이 인공지능과 빅데이터를 활용하는 다양한 곳에서 활약하고 있습니다. 어떤 일들을 하고 있는지 알아볼까요?"
